version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container/nginx/conf.d/default-compose.conf:/etc/nginx/conf.d/default.conf:ro
      - ./container/nginx/conf.d/tls.crt:/etc/nginx/conf.d/tls.crt:ro
      - ./container/nginx/conf.d/tls.key:/etc/nginx/conf.d/tls.key:ro
      - static:/var/www/html
    tmpfs:
      - /var/cache/nginx:uid=82,mode=700
      - /tmp:uid=82,mode=700
    ports:
      - "443:8443"
    read_only: true
    user: "82"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "1"

  attestationapp:
    build:
      context: ./container/attestationserver/
    restart: always
    volumes:
      - static:/var/www/html
    tmpfs:
      - /tmp:uid=1000,mode=700
    env_file:
      - ./mailsettings.env
    read_only: true
    user: "1000"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "1"


volumes:
  static:

networks:
  default: