apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: attestation

resources:
- manifests/namespace.yaml
- manifests/serviceaccount.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml

configMapGenerator:
- name: attestation-server-nginx-conf
  files:
  - container/nginx/nginx.conf
  - container/nginx/conf.d/default-k8s.conf
  - container/nginx/conf.d/headers.include

secretGenerator:
- name: attestation-mailsettings
  env: mailsettings.env
  type: Opaque
images:
  - name: nginx
    newTag: stable-alpine
  - name: attestation-server
    newTag: 1531d7dc4ba1f861515a6caaa7fc7fa6273e89d5
